### ISSUE TITLE
Need Enhancement - Multiples instances - Not thread safe av_Codec call

### ISSUE THREAD

**Issue by spawnrider** [mooncatventures-group/ffmpegDecoder#3]
Hi,

I want to read multiple streams together but there is cgimageDelegate and avcodec issues. 
I think ffmpegDecoder calls to avcodec_open/close() need thread locking.

Could you provide us an enhancement ?

**Comment by mooncatventures-group** [comment]
What are you trying to use:

videoFrameExtractor - that depreciated

You can use fframes-test-beta1 or even better yet streammorePlay which uses no
delegate.

All depends what your trying to do.

**Comment by spawnrider** [comment]
Thanks for your quick answer! I want to realize an IP webcam streams (6x) viewer.
Could you provide StreamMorePlay.framework sources because I can't compile AVDemoPlay2L project for Armv7s architecture :(

**Comment by spawnrider** [comment]
Ok, sorry for the inconvenience. 
I done the job with frameworks from AVDemoPlay2L project :)

**Comment by mooncatventures-group** [comment]
yes for now you must go into build settings and remove armv7s arch, it will have little affect on performance.
A future version in testing will support armv7s and have a lot of new feature.

AVDemoPlay2l is a great starting point for your project, enjoy
