### ISSUE TITLE
EXC_BAD_ACCESS in GLPlayer setupAudioDecoder - Strema with no audio content

### ISSUE THREAD

**Issue by spawnrider** [mooncatventures-group/ffmpegDecoder#4]
Hi,

When stream has no audio content, I have the following issue : EXC_BAD_ACCESS (code=1, address=0x54).

Thrad Stack : 
#0  0x005968a6 in -[GLPlayer setupAudioDecoder] at /Users/michelleC/ev/SDL-1.35517/Xcode-iPhoneOS/testflight/StreamMorePlay copy/StreamMorePlay/GLPlayer.m:777
#1  0x0059446e in -[GLPlayer initWithFrame:movie:aspectRatio:useTCP:] at /Users/michelleC/ev/SDL-1.35517/Xcode-iPhoneOS/testflight/StreamMorePlay copy/StreamMorePlay/GLPlayer.m:267

Call stack :
0x5968a6:  str    r1, [r2, #84]
0x5968a8:  ldr    r1, [sp, #8]
0x5968aa:  ldr    r2, [pc, #16]             ; -[GLPlayer setupAudioDecoder] + 444 at GLPlayer.m:781

There is a possibility to switch off audio parsing/decoding ?

**Comment by mooncatventures-group** [comment]
Short answer : we've done this for some clients

Long answer, is finding the time, were on Facebook, we should get a dialog going and discuss your needs

**Comment by spawnrider** [comment]
Ok, I well understood your point of view. If you can release the current source code or do a short modification to manage the lake of audio in streams, I will be very grateful. 

My need is to show many IP camera streams in a same view. These streams have no audio, just H.264 video content.

**Comment by mooncatventures-group** [comment]
Please join this group and we can discuss.

https://www.facebook.com/groups/mooncatventures/

I don't normally release the source to our commercial offerings , I do make exceptions but I'd like to know the intended purpose of the applications that use it.
We do offer consulting but if all you want is a simple audio modifications we have been doing for our paying clients I am willing to discuss.

Lets discuss this, since I don't have the time I am considering just letting you make the modification you need. I can show you where. its one line code changes in 3 places in GLPlayer

**Comment by spawnrider** [comment]
Ok, just let me know where to do the modification and I will do it. Thanks a lot for your time and your help! I appreciate this:)

**Comment by RSully** [comment]
It's too bad this was never published. Kind of defeats the whole idea of GitHub and social coding.

**Comment by mooncatventures-group** [comment]
Not  sure what your point is, I think the number of repositories we have kind of says volumes about our commitment to open source.

Ours is a very tiny company, and all my personal revenue for important things like keeping my family fed come from our commercial consulting work.
The offerings here are made when I have time to take away from a very busy development schedule. its not unreasonable to expect audio+video . True we have found this to be a bit of a omission and have corrected it with streamMorePlay but StreamMorePlay has taken a completely different track from what is here. We do have plans to open source a version of StreamMorePlay , we just don't have the time right now. If there is something specific you are looking for please let me know, perhaps we can share some code with you and in the spirt of social coding (whatever that is) YOU can publish the changes you make.

**Comment by RSully** [comment]
Let me apologize, I didn't mean any of that with a condescending tone, I am sorry if it came off like that. I certainly understand that life gets in the way of things and for many opensource is a gift to be able to partake in if there is any time left over from a busy week. I was just browsing looking for snippets of some code I was working on and your repository caught my eye; I didn't think much of leaving a comment. Of course any code published can only be of help, and if you do share more code in the future I'll be sure to take a look. 

The only other thing I'd like to bring up is the lack of a license on a couple of your repositories, but no worries :smiley:.

**Comment by mooncatventures-group** [comment]
No hard feelings, please feel free to join our app developers group, there are a lot of stream developers in there, I'm sure you could get answer to any question you might have. , and its the perfect place to ask for code that isn't quite ready for open source, but isn't exactly closed source either. https://www.facebook.com/groups/mooncatventures/
